### ISSUE TITLE
Colaboradores

### ISSUE THREAD

**Issue by garcaplay** [GDGLaRioja/zurracapoteconf#7]
Añadir los colaboradores que faltan.
Tienen que ir dando la info.

**Comment by edualfonso** [comment]
Eduardo
Organizer del GDG La Rioja, ITI Electrónica, inquietud por el mundo maker desde que hice un motor eléctrico el la EGB , aprendí basic con un ordenador Dragón en las bajeras del Ayuntamiento de Logroño, dibujo 3D desde que tenia un 486. 
Profesionalmente casi he conseguido abandonar el gremio, pero estas cosas…. me tiran mucho.


![Eduardo_Alfonso](https://user-images.githubusercontent.com/7362143/154799089-b60eee10-c13e-4e9f-967c-2ce673e8d3f7.jpg)
